require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
  TargetRubyVersion: 3.1.3
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false
