require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-minitest
  - rubocop-thread_safety
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  SuggestExtensions: false

  Exclude:
    - "**/vendor/**/*"
    - "**/tmp/**/*"
    - "**/node_modules/**/*"
    - "**/.git/**/*"
    - "**/bin/**/*"
    - "**/spec/fixtures/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
